"""Initial

Revision ID: 3c59cb6e04e4
Revises: 
Create Date: 2022-08-08 19:16:35.870504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy import Enum


# revision identifiers, used by Alembic.
revision = '3c59cb6e04e4'
down_revision = None
branch_labels = None
depends_on = None

UnitType = Enum('OFFER', 'CATEGORY', name='type')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', UnitType, nullable=False),
    sa.Column('parentId', UUID(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__items'))
    )
    op.create_table('relations',
    sa.Column('unit_id', UUID(), nullable=False),
    sa.Column('relative_id', UUID(), nullable=False),
    sa.PrimaryKeyConstraint('unit_id', 'relative_id', name=op.f('pk__relations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relations')
    op.drop_table('items')
    # ### end Alembic commands ###
